# Generated by Django 4.1.1 on 2022-09-09 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birthdate", models.DateField()),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("function", models.CharField(max_length=200)),
                ("hiring_date", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
